#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Path Finder$" manage=off
#yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
#yabai -m rule --add app="Fantastical" manage=off
#yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
#yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
#yabai -m rule --add app="^perl_client_app$" manage=off
yabai -m rule --add app="^console$" manage=off
#yabai -m rule --add app="^Harvest$" manage=off
#yabai -m rule --add app="^CiscoSparkHelper$" manage=off
#yabai -m rule --add app="^Logi Options$" manage=off
#yabai -m rule --add app="^Cisco Webex Start$" manage=off
#yabai -m rule --add app="^Private Internet Access$" manage=off
#yabai -m rule --add app="^uTools$" manage=off
# bar settings
# 打开状态栏
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
# 使用font-awesome替代罗马数字
yabai -m config status_bar_space_icon_strip                8 9  
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          1
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings(设置间隔,都设置成0)
yabai -m config layout                       bsp
yabai -m config top_padding                  35
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

echo "yabai configuration loaded.."


# spacebar icon
yabai -m space 1 --label I
yabai -m space 2 --label II
yabai -m space 3 --label III
yabai -m space 4 --label IV
yabai -m space 5 --label V
yabai -m space 6 --label VI
yabai -m space 7 --label VII
yabai -m space 8 --label VIII
yabai -m space 9 --label IX
yabai -m space 10 --label X


#yabai -m rule --add app="Safari"        space=3
#yabai -m rule --add app="^Brave$"        space=3
#yabai -m rule --add app="^ 网易云音乐 $"        space=6
yabai -m rule --add app="^Obsidian$"        space=3
yabai -m rule --add app="^ 提醒事项 $"        space=4
yabai -m rule --add app="^Reminders$"        space=4


#app 
otherApp='^(访达|uTools|utools|Utools|uTools|Calendar|日历|Cubox Helper|Cubox 助手)$'
yabai -m rule --add app="${otherApp}" manage=off
